name: Deploy Vue Project

on:
  push:
    branches:
      - main  # 当你向 main 分支推送代码时触发此流程

# 给予该流程写入仓库内容的权限
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 检出代码
        uses: actions/checkout@v4

      - name: Setup Node.js 设置 Node 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20 # 使用 Node 20
          cache: 'npm'

      - name: Install dependencies 安装依赖
        run: npm install

      - name: Build 打包项目
        run: npm run build

      - name: Deploy to GitHub Pages 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vue 打包后的目录名为 dist
          branch: gh-pages # 将打包后的文件部署到 gh-pages 分支